site_name: xgeeks-ai-starter-demo
site_description: "Main documentation for xgeeks-ai-starter-demo project"
repo_url: https://github.com/xgeekshq/xgeeks-ai-starter-demo.git
edit_uri: edit/master/docs

# plugins:
#   - techdocs-core

# For sidebar navigation
nav:
  - Overview: "index.md"
  - Getting Started: "getting-started/getting-started.md"
